name: Docker + Ngrok v3 Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
  if: false
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del codi
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Llançar contenidors amb Docker Compose (plugin integrat)
      - name: Run Docker containers
        run: docker compose up -d

      # 3️⃣ Instal·lar Ngrok v3
      - name: Install Ngrok v3
        run: |
          curl -sLo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -o ngrok.zip
          sudo mv ngrok /usr/local/bin/
          sudo chmod +x /usr/local/bin/ngrok
          /usr/local/bin/ngrok version

      # 4️⃣ Autenticar Ngrok amb el secret
      - name: Authenticate Ngrok
        run: /usr/local/bin/ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      # 5️⃣ Llançar el túnel ngrok i capturar la URL pública
      - name: Start Ngrok tunnel
        id: ngrok
        run: |
          # Llança ngrok en background
          /usr/local/bin/ngrok http 8080 --log=stdout > ngrok.log &
          NGROK_PID=$!
          
          # Espera que ngrok arranqui
          sleep 5
          
          # Extreu la URL pública des del endpoint local
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | \
                       grep -oP '"public_url":"\Khttps://[^"]+')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
          echo "🌐 Web accessible a: $NGROK_URL"
          echo "::notice title=URL pública::$NGROK_URL"

          # Manté el túnel actiu fins que acabi el workflow (10 minuts)
          sleep 600
          kill $NGROK_PID

      # 6️⃣ Neteja dels contenidors Docker al final
      - name: Stop Docker containers
        if: always()
        run: docker compose down
